name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        test_type:
          - "core"
        include:
          - experimental: false
          - python-version: "3.12"
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          python-allow-prereleases: ${{ matrix.experimental }}
          poetry-version: "1.6.1"
          cache-key: ${{ matrix.test_type }}
          install-command: |
              if [ "${{ matrix.test_type }}" == "core" ]; then
                echo "Running core tests, installing dependencies with poetry..."
                poetry install --only=main,test
              else
                echo "Running extended tests, installing dependencies with poetry..."
                poetry install --only=main,test --all-extras
              fi
      - name: Run ${{matrix.test_type}} tests
        run: |
          if [ "${{ matrix.test_type }}" == "core" ]; then
            make test
          else
            make extended_tests
          fi
        shell: bash
